### ISSUE TITLE
Threads per client in case of scaling Marathon app

### ISSUE THREAD

**Issue by beenum22** [lake-lerna/hCassandra#7]
Hi,
I have a question regarding scalability when the number of clients increases. We are running requested number of clients in different threads. Maximum number of threads we can run per client is 20 and if the user inputs client number more than 20, we are scaling the marathon app accordingly. When the client number is greater than 20, we decide ‘threads per client’ to be equal to 20 and scale the app according to the value we get from

> client_count = math.ceil(self.options.total_client_count / max_threads_per_client)

I’m confused about one detail though, the scaled app gets the same arguments as the initial marathon app which means rest of the scaled apps will run 20 threads per client too, right? 
Let’s say the user asked for 21 clients, In this case, we scale it to 2 apps with 20 threads running per client. Why are we running 40 threads while the user asked for only 21?
Correct me if I’m missing any detail. If I’m right, I have a simple workaround to reduce that number.
Thanks

**Comment by annym** [comment]
Hi, 

   @beenum22 I took a look on this and yes you are right. As it is now we round up and keep the same number of threads per marathon app. So in the example of the 21 clients we would scale to 2 apps with 20 threads each. We can definitely include the workaround you suggest to cover these scenarios.

**Comment by beenum22** [comment]
Hi,
Okay I will push the changes I made. Although it's not a complete fix but it reduces the number of extra threads with just one additional line of code.
Thanks
